openapi: 3.0.0
info:
  title: Federated Data Sharing Strawman with Application Flow OAuth2
  description: A set of APIs to support different levels of data sharing. A service
    that implements this API can participate in a wider network.
  version: "1.1"
servers:
- url: https://localhost:8443/aridhia/federated-data-sharing/1.0.0/
  description: ADDI Federated Data Sharing Common API Strawman
paths:
  /datasets/:
    get:
      summary: Get a List of Datasets that can be Filtered
      description: Returns a list of datasets within the Dataset Registry
      operationId: datasets_get
      parameters:
      - name: doi
        in: query
        description: The DOI of the dataset
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: title
        in: query
        description: The title of the dataset
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: author
        in: query
        description: The specified author of the dataset
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: description
        in: query
        description: The description of the dataset
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: organisation
        in: query
        description: The description of the dataset
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: tag_key
        in: query
        description: The tag key applied to the dataset
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: tag_value
        in: query
        description: The tag key applied to the dataset
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/datasets_list'
        "401":
          description: Unauthorized (401)
      x-openapi-router-controller: swagger_server.controllers.metadata_controller
  /datasets/{datasetid}/catalogue:
    get:
      summary: Get Catalogue Entry (Metadata) for Dataset
      description: Returns a DCAT dataset catalogue entry
      operationId: datasets_datasetid_catalogue_get
      parameters:
      - name: datasetid
        in: path
        description: Dataset ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DCAT_metadata'
        "401":
          description: Unauthorized (401)
        "404":
          description: Not Found (404) - Dataset not found.
      x-openapi-router-controller: swagger_server.controllers.metadata_controller
  /datasets/{datasetid}/dictionary:
    get:
      summary: Get a Dataset Definition
      description: Obtain a dataset definition (adhering to the schema.org vocabulary)
      operationId: datasets_datasetid_dictionary_get
      parameters:
      - name: datasetid
        in: path
        description: Dataset ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/data_dictionary'
        "401":
          description: Unauthorized (401)
        "404":
          description: Not Found (404) - Dataset not found.
      x-openapi-router-controller: swagger_server.controllers.metadata_controller
components:
  schemas:
    datasets_list:
      required:
      - datasets
      type: object
      properties:
        datasets:
          type: array
          items:
            $ref: '#/components/schemas/dataset_id'
      example:
        datasets:
        - author: author
          id: id
          dataset_name: dataset_name
        - author: author
          id: id
          dataset_name: dataset_name
    dataset_id:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        dataset_name:
          type: string
        author:
          type: string
      example:
        author: author
        id: id
        dataset_name: dataset_name
    DCAT_metadata:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        creator:
          type: string
        contactPoint:
          type: string
        publisher:
          $ref: '#/components/schemas/DCAT_metadata_publisher'
        license:
          type: string
        versionInfo:
          type: string
        additionalProperties:
          type: object
      example:
        license: license
        creator: creator
        contactPoint: contactPoint
        description: description
        publisher:
          name: name
          url: url
        id: id
        versionInfo: versionInfo
        additionalProperties: {}
        title: title
    data_dictionary:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/data_dictionary_field'
        lookups:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/data_dictionary_lookup'
      example:
        lookups:
          key:
            name: name
            description: description
        id: id
        fields:
        - name: name
          description: description
          label: label
          type: type
          constraints: constraints
        - name: name
          description: description
          label: label
          type: type
          constraints: constraints
    data_dictionary_field:
      required:
      - label
      - name
      - type
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        type:
          type: string
        description:
          type: string
        constraints:
          type: string
      example:
        name: name
        description: description
        label: label
        type: type
        constraints: constraints
    data_dictionary_lookup:
      type: array
      items:
        $ref: '#/components/schemas/data_dictionary_lookup_inner'
    DCAT_metadata_publisher:
      required:
      - name
      - url
      type: object
      properties:
        name:
          type: string
        url:
          type: string
      example:
        name: name
        url: url
    data_dictionary_lookup_inner:
      required:
      - description
      - name
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      example:
        name: name
        description: description
  securitySchemes:
    oAuth2Implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          scopes:
            api://53b6b40b-ac95-4a38-95a8-f264a93494e4/read_api: allows reading resources
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_oAuth2Implicit
      x-scopeValidateFunc: swagger_server.controllers.authorization_controller.validate_scope_oAuth2Implicit

